package utils.sql;

public class InitSql {

    public static final String initial =
            "DROP TABLE IF EXISTS ticket;\r\n"
                    + "DROP TABLE IF EXISTS reservation;\r\n"
                    + "DROP TABLE IF EXISTS member;\r\n"
                    + "DROP TABLE IF EXISTS seat;\r\n"
                    + "DROP TABLE IF EXISTS screening_schedule;\r\n"
                    + "DROP TABLE IF EXISTS screen;\r\n"
                    + "DROP TABLE IF EXISTS movie;"
                    + "CREATE TABLE IF NOT EXISTS `movie` (\r\n"
                    + "  `id` BIGINT NOT NULL AUTO_INCREMENT,\r\n"
                    + "  `title` VARCHAR(45) NULL,\r\n"
                    + "  `running_time` INT NULL,\r\n"
                    + "  `director` VARCHAR(45) NULL,\r\n"
                    + "  `actor` VARCHAR(45) NULL,\r\n"
                    + "  `genre` VARCHAR(45) NULL,\r\n"
                    + "  `description` VARCHAR(45) NULL,\r\n"
                    + "  `release_date` DATE NULL,\r\n"
                    + "  `rating` DOUBLE NULL,\r\n"
                    + "  `age_limit` INT NULL,\r\n"
                    + "  PRIMARY KEY (`id`))\r\n"
                    + "ENGINE = InnoDB;\r\n"
                    + "\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "-- Table `mydb`.`screen`\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "CREATE TABLE IF NOT EXISTS `screen` (\r\n"
                    + "  `id` BIGINT NOT NULL AUTO_INCREMENT,\r\n"
                    + "  `seat_count` INT NULL,\r\n"
                    + "  `is_used` TINYINT NULL,\r\n"
                    + "  `column_seats` INT NULL,\r\n"
                    + "  `row_seats` INT NULL,\r\n"
                    + "  PRIMARY KEY (`id`))\r\n"
                    + "ENGINE = InnoDB;\r\n"
                    + "\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "-- Table `mydb`.`screening_schedule`\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "CREATE TABLE IF NOT EXISTS `screening_schedule` (\r\n"
                    + "  `id` BIGINT NOT NULL AUTO_INCREMENT,\r\n"
                    + "  `start_date` DATE NULL,\r\n"
                    + "  `day_of_week` VARCHAR(45) NULL,\r\n"
                    + "  `round` INT NULL,\r\n"
                    + "  `start_time` TIME NULL,\r\n"
                    + "  `movie_id` BIGINT NOT NULL,\r\n"
                    + "  `screen_id` BIGINT NOT NULL,\r\n"
                    + "  `selling_price` INT NULL,\r\n"
                    + "  `standard_price` INT NULL,\r\n"
                    + "  PRIMARY KEY (`id`),\r\n"
                    + "  INDEX `fk_screening_schedule_movie_idx` (`movie_id` ASC) VISIBLE,\r\n"
                    + "  INDEX `fk_screening_schedule_cinema1_idx` (`screen_id` ASC) VISIBLE,\r\n"
                    + "  CONSTRAINT `fk_screening_schedule_movie`\r\n"
                    + "    FOREIGN KEY (`movie_id`)\r\n"
                    + "    REFERENCES `movie` (`id`)\r\n"
                    + "    ON DELETE NO ACTION\r\n"
                    + "    ON UPDATE NO ACTION,\r\n"
                    + "  CONSTRAINT `fk_screening_schedule_cinema1`\r\n"
                    + "    FOREIGN KEY (`screen_id`)\r\n"
                    + "    REFERENCES `screen` (`id`)\r\n"
                    + "    ON DELETE NO ACTION\r\n"
                    + "    ON UPDATE NO ACTION)\r\n"
                    + "ENGINE = InnoDB;\r\n"
                    + "\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "-- Table `mydb`.`seat`\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "CREATE TABLE IF NOT EXISTS `seat` (\r\n"
                    + "  `id` BIGINT NOT NULL AUTO_INCREMENT,\r\n"
                    + "  `is_used` TINYINT NULL,\r\n"
                    + "  `row_num` INT NULL,\r\n"
                    + "  `column_num` INT NULL,\r\n"
                    + "  `screen_id` BIGINT NOT NULL,\r\n"
                    + "  PRIMARY KEY (`id`),\r\n"
                    + "  INDEX `fk_seat_screen1_idx` (`screen_id` ASC) VISIBLE,\r\n"
                    + "  CONSTRAINT `fk_seat_screen1`\r\n"
                    + "    FOREIGN KEY (`screen_id`)\r\n"
                    + "    REFERENCES `screen` (`id`)\r\n"
                    + "    ON DELETE NO ACTION\r\n"
                    + "    ON UPDATE NO ACTION)\r\n"
                    + "ENGINE = InnoDB;\r\n"
                    + "\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "-- Table `mydb`.`member`\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "CREATE TABLE IF NOT EXISTS `member` (\r\n"
                    + "  `id` BIGINT NOT NULL AUTO_INCREMENT,\r\n"
                    + "  `name` VARCHAR(45) NULL,\r\n"
                    + "  `phone_number` VARCHAR(45) NULL,\r\n"
                    + "  `email` VARCHAR(45) NULL,\r\n"
                    + "  PRIMARY KEY (`id`))\r\n"
                    + "ENGINE = InnoDB;\r\n"
                    + "\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "-- Table `mydb`.`reservation`\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "CREATE TABLE IF NOT EXISTS `reservation` (\r\n"
                    + "  `id` BIGINT NOT NULL AUTO_INCREMENT,\r\n"
                    + "  `payment_method` VARCHAR(45) NULL,\r\n"
                    + "  `payment_status` TINYINT NULL,\r\n"
                    + "  `payment_amount` INT NULL,\r\n"
                    + "  `payment_date` DATE NULL,\r\n"
                    + "  `member_id` BIGINT NOT NULL,\r\n"
                    + "  PRIMARY KEY (`id`),\r\n"
                    + "  INDEX `fk_reservation_member1_idx` (`member_id` ASC) VISIBLE,\r\n"
                    + "  CONSTRAINT `fk_reservation_member1`\r\n"
                    + "    FOREIGN KEY (`member_id`)\r\n"
                    + "    REFERENCES `member` (`id`)\r\n"
                    + "    ON DELETE NO ACTION\r\n"
                    + "    ON UPDATE NO ACTION)\r\n"
                    + "ENGINE = InnoDB;\r\n"
                    + "\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "-- Table `mydb`.`ticket`\r\n"
                    + "-- -----------------------------------------------------\r\n"
                    + "CREATE TABLE IF NOT EXISTS `ticket` (\r\n"
                    + "  `id` BIGINT NOT NULL AUTO_INCREMENT,\r\n"
                    + "  `is_ticketed` TINYINT NULL,\r\n"
                    + "  `screening_schedule_id` BIGINT NOT NULL,\r\n"
                    + "  `seat_id` BIGINT NOT NULL,\r\n"
                    + "  `reservation_id` BIGINT NOT NULL,\r\n"
                    + "  `screen_id` BIGINT NOT NULL,\r\n"
                    + "  PRIMARY KEY (`id`),\r\n"
                    + "  INDEX `fk_ticket_screening_schedule1_idx` (`screening_schedule_id` ASC) VISIBLE,\r\n"
                    + "  INDEX `fk_ticket_seat1_idx` (`seat_id` ASC) VISIBLE,\r\n"
                    + "  INDEX `fk_ticket_reservation1_idx` (`reservation_id` ASC) VISIBLE,\r\n"
                    + "  INDEX `fk_ticket_screen1_idx` (`screen_id` ASC) VISIBLE,\r\n"
                    + "  CONSTRAINT `fk_ticket_screening_schedule1`\r\n"
                    + "    FOREIGN KEY (`screening_schedule_id`)\r\n"
                    + "    REFERENCES `screening_schedule` (`id`)\r\n"
                    + "    ON DELETE NO ACTION\r\n"
                    + "    ON UPDATE NO ACTION,\r\n"
                    + "  CONSTRAINT `fk_ticket_seat1`\r\n"
                    + "    FOREIGN KEY (`seat_id`)\r\n"
                    + "    REFERENCES `seat` (`id`)\r\n"
                    + "    ON DELETE NO ACTION\r\n"
                    + "    ON UPDATE NO ACTION,\r\n"
                    + "  CONSTRAINT `fk_ticket_reservation1`\r\n"
                    + "    FOREIGN KEY (`reservation_id`)\r\n"
                    + "    REFERENCES `reservation` (`id`)\r\n"
                    + "    ON DELETE NO ACTION\r\n"
                    + "    ON UPDATE NO ACTION,\r\n"
                    + "  CONSTRAINT `fk_ticket_screen1`\r\n"
                    + "    FOREIGN KEY (`screen_id`)\r\n"
                    + "    REFERENCES `screen` (`id`)\r\n"
                    + "    ON DELETE NO ACTION\r\n"
                    + "    ON UPDATE NO ACTION)\r\n"
                    + "ENGINE = InnoDB;"
                    + "INSERT INTO movie (title, running_time, director, actor, genre, description, release_date, rating, age_limit)\r\n"
                    + "VALUES\r\n"
                    + "('기생충', 132, '봉준호', '송강호, 이선균, 조여정', '드라마, 코미디', '두 가족의 이야기를 통해 계급 차이를 그린 영화', '2019-05-30', 8.6, 15),\r\n"
                    + "('부산행', 118, '연상호', '공유, 정유미, 마동석', '액션, 스릴러', '부산을 향하는 기차 안에서 벌어지는 좀비 사태를 다룬 영화', '2016-07-20', 7.5, 15),\r\n"
                    + "('올드보이', 120, '박찬욱', '최민식, 유지태', '스릴러, 드라마', '15년 간의 감금 후 복수를 추구하는 남자의 이야기', '2003-11-21', 8.4, 18),\r\n"
                    + "('괴물', 119, '봉준호', '송강호, 변희봉', '드라마, 공포', '한강에서 나타난 괴물과 한 가족의 싸움을 그린 영화', '2006-07-27', 7.1, 12),\r\n"
                    + "('추격자', 125, '나홍진', '김윤석, 하정우', '스릴러, 범죄', '전직 형사가 연쇄 살인범을 추격하는 이야기', '2008-02-14', 7.9, 18),\r\n"
                    + "('베테랑', 123, '류승완', '황정민, 유아인', '액션, 드라마', '부패한 재벌 3세와 맞서 싸우는 형사의 이야기', '2015-08-05', 7.2, 15),\r\n"
                    + "('아가씨', 144, '박찬욱', '김민희, 하정우', '드라마, 로맨스', '1930년대 일제 강점기를 배경으로 한 미스터리 로맨스', '2016-06-01', 8.1, 18),\r\n"
                    + "('타짜', 139, '최동훈', '조승우, 김혜수', '드라마, 범죄', '도박으로 세상의 부를 얻으려는 사람들의 이야기', '2006-09-28', 7.3, 18),\r\n"
                    + "('해운대', 120, '윤제균', '설경구, 하지원', '드라마, 재난', '해운대에 몰아치는 쓰나미를 배경으로 한 재난 영화', '2009-07-22', 5.7, 12),\r\n"
                    + "('7번방의 선물', 127, '이환경', '류승룡, 박신혜', '드라마, 코미디', '지능 장애인 아버지와 그의 딸 이야기', '2013-01-23', 8.2, 12),\r\n"
                    + "('왕의 남자', 119, '이준익', '감우성, 정진영', '드라마, 역사', '조선 시대 궁중에서 벌어지는 이야기', '2005-12-29', 7.5, 12),\r\n"
                    + "('공동경비구역 JSA', 110, '박찬욱', '이병헌, 송강호, 신하균', '드라마, 스릴러', '남북한 접경 지역에서 벌어지는 사건을 다룬 영화', '2000-09-09', 8.3, 15);\r\n"
                    + "\r\n"
                    + "INSERT INTO screen (seat_count, is_used, column_seats, row_seats)\r\n"
                    + "VALUES\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5),\r\n"
                    + "(25, 1, 5, 5);\r\n"
                    + "\r\n"
                    + "INSERT INTO screening_schedule (start_date, day_of_week, round, start_time, movie_id, screen_id, selling_price, standard_price)\r\n"
                    + "VALUES\r\n"
                    + "('2023-05-10', '수요일', 1, '12:00:00', 1, 1, 12000, 10000),\r\n"
                    + "('2023-05-10', '수요일', 2, '15:00:00', 2, 1, 12000, 10000),\r\n"
                    + "('2023-05-10', '수요일', 3, '18:00:00', 3, 2, 15000, 12000),\r\n"
                    + "('2023-05-11', '목요일', 1, '12:00:00', 4, 3, 11000, 9000),\r\n"
                    + "('2023-05-11', '목요일', 2, '15:00:00', 5, 4, 13000, 11000),\r\n"
                    + "('2023-05-11', '목요일', 3, '18:00:00', 6, 5, 14000, 12000),\r\n"
                    + "('2023-05-12', '금요일', 1, '12:00:00', 7, 6, 12000, 10000),\r\n"
                    + "('2023-05-12', '금요일', 2, '15:00:00', 8, 7, 11000, 9000),\r\n"
                    + "('2023-05-12', '금요일', 3, '18:00:00', 9, 8, 10000, 8000),\r\n"
                    + "('2023-05-13', '토요일', 1, '12:00:00', 10, 9, 13000, 11000),\r\n"
                    + "('2023-05-13', '토요일', 2, '15:00:00', 11, 10, 15000, 12000),\r\n"
                    + "('2023-05-13', '토요일', 3, '18:00:00', 12, 11, 14000, 12000);\r\n"
                    + "\r\n"
                    + "INSERT INTO seat (is_used, row_num, column_num, screen_id)\r\n"
                    + "VALUES\r\n"
                    + "(0, 1, 1, 1),\r\n"
                    + "(0, 1, 2, 1),\r\n"
                    + "(0, 1, 3, 1),\r\n"
                    + "(0, 1, 4, 1),\r\n"
                    + "(0, 1, 5, 1),\r\n"
                    + "(0, 2, 1, 1),\r\n"
                    + "(0, 2, 2, 1),\r\n"
                    + "(0, 2, 3, 1),\r\n"
                    + "(0, 2, 4, 1),\r\n"
                    + "(0, 2, 5, 1),\r\n"
                    + "(0, 3, 1, 1),\r\n"
                    + "(0, 3, 2, 1),\r\n"
                    + "(0, 3, 3, 1),\r\n"
                    + "(0, 3, 4, 1),\r\n"
                    + "(0, 3, 5, 1),\r\n"
                    + "(0, 4, 1, 1),\r\n"
                    + "(0, 4, 2, 1),\r\n"
                    + "(0, 4, 3, 1),\r\n"
                    + "(0, 4, 4, 1),\r\n"
                    + "(0, 4, 5, 1),\r\n"
                    + "(0, 5, 1, 1),\r\n"
                    + "(0, 5, 2, 1),\r\n"
                    + "(0, 5, 3, 1),\r\n"
                    + "(0, 5, 4, 1),\r\n"
                    + "(0, 5, 5, 1),\r\n"
                    + "(0, 1, 1, 2),\r\n"
                    + "(0, 1, 2, 2),\r\n"
                    + "(0, 1, 3, 2),\r\n"
                    + "(0, 1, 4, 2),\r\n"
                    + "(0, 1, 5, 2),\r\n"
                    + "(0, 2, 1, 2),\r\n"
                    + "(0, 2, 2, 2),\r\n"
                    + "(0, 2, 3, 2),\r\n"
                    + "(0, 2, 4, 2),\r\n"
                    + "(0, 2, 5, 2),\r\n"
                    + "(0, 3, 1, 2),\r\n"
                    + "(0, 3, 2, 2),\r\n"
                    + "(0, 3, 3, 2),\r\n"
                    + "(0, 3, 4, 2),\r\n"
                    + "(0, 3, 5, 2),\r\n"
                    + "(0, 4, 1, 2),\r\n"
                    + "(0, 4, 2, 2),\r\n"
                    + "(0, 4, 3, 2),\r\n"
                    + "(0, 4, 4, 2),\r\n"
                    + "(0, 4, 5, 2),\r\n"
                    + "(0, 5, 1, 2),\r\n"
                    + "(0, 5, 2, 2),\r\n"
                    + "(0, 5, 3, 2),\r\n"
                    + "(0, 5, 4, 2),\r\n"
                    + "(0, 5, 5, 2),\r\n"
                    + "(0, 1, 1, 3),\r\n"
                    + "(0, 1, 2, 3),\r\n"
                    + "(0, 1, 3, 3),\r\n"
                    + "(0, 1, 4, 3),\r\n"
                    + "(0, 1, 5, 3),\r\n"
                    + "(0, 2, 1, 3),\r\n"
                    + "(0, 2, 2, 3),\r\n"
                    + "(0, 2, 3, 3),\r\n"
                    + "(0, 2, 4, 3),\r\n"
                    + "(0, 2, 5, 3),\r\n"
                    + "(0, 3, 1, 3),\r\n"
                    + "(0, 3, 2, 3),\r\n"
                    + "(0, 3, 3, 3),\r\n"
                    + "(0, 3, 4, 3),\r\n"
                    + "(0, 3, 5, 3),\r\n"
                    + "(0, 4, 1, 3),\r\n"
                    + "(0, 4, 2, 3),\r\n"
                    + "(0, 4, 3, 3),\r\n"
                    + "(0, 4, 4, 3),\r\n"
                    + "(0, 4, 5, 3),\r\n"
                    + "(0, 5, 1, 3),\r\n"
                    + "(0, 5, 2, 3),\r\n"
                    + "(0, 5, 3, 3),\r\n"
                    + "(0, 5, 4, 3),\r\n"
                    + "(0, 5, 5, 3),\r\n"
                    + "(0, 1, 1, 4),\r\n"
                    + "(0, 1, 2, 4),\r\n"
                    + "(0, 1, 3, 4),\r\n"
                    + "(0, 1, 4, 4),\r\n"
                    + "(0, 1, 5, 4),\r\n"
                    + "(0, 2, 1, 4),\r\n"
                    + "(0, 2, 2, 4),\r\n"
                    + "(0, 2, 3, 4),\r\n"
                    + "(0, 2, 4, 4),\r\n"
                    + "(0, 2, 5, 4),\r\n"
                    + "(0, 3, 1, 4),\r\n"
                    + "(0, 3, 2, 4),\r\n"
                    + "(0, 3, 3, 4),\r\n"
                    + "(0, 3, 4, 4),\r\n"
                    + "(0, 3, 5, 4),\r\n"
                    + "(0, 4, 1, 4),\r\n"
                    + "(0, 4, 2, 4),\r\n"
                    + "(0, 4, 3, 4),\r\n"
                    + "(0, 4, 4, 4),\r\n"
                    + "(0, 4, 5, 4),\r\n"
                    + "(0, 5, 1, 4),\r\n"
                    + "(0, 5, 2, 4),\r\n"
                    + "(0, 5, 3, 4),\r\n"
                    + "(0, 5, 4, 4),\r\n"
                    + "(0, 5, 5, 4),\r\n"
                    + "(0, 1, 1, 5),\r\n"
                    + "(0, 1, 2, 5),\r\n"
                    + "(0, 1, 3, 5),\r\n"
                    + "(0, 1, 4, 5),\r\n"
                    + "(0, 1, 5, 5),\r\n"
                    + "(0, 2, 1, 5),\r\n"
                    + "(0, 2, 2, 5),\r\n"
                    + "(0, 2, 3, 5),\r\n"
                    + "(0, 2, 4, 5),\r\n"
                    + "(0, 2, 5, 5),\r\n"
                    + "(0, 3, 1, 5),\r\n"
                    + "(0, 3, 2, 5),\r\n"
                    + "(0, 3, 3, 5),\r\n"
                    + "(0, 3, 4, 5),\r\n"
                    + "(0, 3, 5, 5),\r\n"
                    + "(0, 4, 1, 5),\r\n"
                    + "(0, 4, 2, 5),\r\n"
                    + "(0, 4, 3, 5),\r\n"
                    + "(0, 4, 4, 5),\r\n"
                    + "(0, 4, 5, 5),\r\n"
                    + "(0, 5, 1, 5),\r\n"
                    + "(0, 5, 2, 5),\r\n"
                    + "(0, 5, 3, 5),\r\n"
                    + "(0, 5, 4, 5),\r\n"
                    + "(0, 5, 5, 5),\r\n"
                    + "\r\n"
                    + "(0, 1, 1, 6),\r\n"
                    + "(0, 1, 2, 6),\r\n"
                    + "(0, 1, 3, 6),\r\n"
                    + "(0, 1, 4, 6),\r\n"
                    + "(0, 1, 5, 6),\r\n"
                    + "(0, 2, 1, 6),\r\n"
                    + "(0, 2, 2, 6),\r\n"
                    + "(0, 2, 3, 6),\r\n"
                    + "(0, 2, 4, 6),\r\n"
                    + "(0, 2, 5, 6),\r\n"
                    + "(0, 3, 1, 6),\r\n"
                    + "(0, 3, 2, 6),\r\n"
                    + "(0, 3, 3, 6),\r\n"
                    + "(0, 3, 4, 6),\r\n"
                    + "(0, 3, 5, 6),\r\n"
                    + "(0, 4, 1, 6),\r\n"
                    + "(0, 4, 2, 6),\r\n"
                    + "(0, 4, 3, 6),\r\n"
                    + "(0, 4, 4, 6),\r\n"
                    + "(0, 4, 5, 6),\r\n"
                    + "(0, 5, 1, 6),\r\n"
                    + "(0, 5, 2, 6),\r\n"
                    + "(0, 5, 3, 6),\r\n"
                    + "(0, 5, 4, 6),\r\n"
                    + "(0, 5, 5, 6),\r\n"
                    + "(0, 1, 1, 7),\r\n"
                    + "(0, 1, 2, 7),\r\n"
                    + "(0, 1, 3, 7),\r\n"
                    + "(0, 1, 4, 7),\r\n"
                    + "(0, 1, 5, 7),\r\n"
                    + "(0, 2, 1, 7),\r\n"
                    + "(0, 2, 2, 7),\r\n"
                    + "(0, 2, 3, 7),\r\n"
                    + "(0, 2, 4, 7),\r\n"
                    + "(0, 2, 5, 7),\r\n"
                    + "(0, 3, 1, 7),\r\n"
                    + "(0, 3, 2, 7),\r\n"
                    + "(0, 3, 3, 7),\r\n"
                    + "(0, 3, 4, 7),\r\n"
                    + "(0, 3, 5, 7),\r\n"
                    + "(0, 4, 1, 7),\r\n"
                    + "(0, 4, 2, 7),\r\n"
                    + "(0, 4, 3, 7),\r\n"
                    + "(0, 4, 4, 7),\r\n"
                    + "(0, 4, 5, 7),\r\n"
                    + "(0, 5, 1, 7),\r\n"
                    + "(0, 5, 2, 7),\r\n"
                    + "(0, 5, 3, 7),\r\n"
                    + "(0, 5, 4, 7),\r\n"
                    + "(0, 5, 5, 7),\r\n"
                    + "(0, 1, 1, 8),\r\n"
                    + "(0, 1, 2, 8),\r\n"
                    + "(0, 1, 3, 8),\r\n"
                    + "(0, 1, 4, 8),\r\n"
                    + "(0, 1, 5, 8),\r\n"
                    + "(0, 2, 1, 8),\r\n"
                    + "(0, 2, 2, 8),\r\n"
                    + "(0, 2, 3, 8),\r\n"
                    + "(0, 2, 4, 8),\r\n"
                    + "(0, 2, 5, 8),\r\n"
                    + "(0, 3, 1, 8),\r\n"
                    + "(0, 3, 2, 8),\r\n"
                    + "(0, 3, 3, 8),\r\n"
                    + "(0, 3, 4, 8),\r\n"
                    + "(0, 3, 5, 8),\r\n"
                    + "(0, 4, 1, 8),\r\n"
                    + "(0, 4, 2, 8),\r\n"
                    + "(0, 4, 3, 8),\r\n"
                    + "(0, 4, 4, 8),\r\n"
                    + "(0, 4, 5, 8),\r\n"
                    + "(0, 5, 1, 8),\r\n"
                    + "(0, 5, 2, 8),\r\n"
                    + "(0, 5, 3, 8),\r\n"
                    + "(0, 5, 4, 8),\r\n"
                    + "(0, 5, 5, 8),\r\n"
                    + "(0, 1, 1, 9),\r\n"
                    + "(0, 1, 2, 9),\r\n"
                    + "(0, 1, 3, 9),\r\n"
                    + "(0, 1, 4, 9),\r\n"
                    + "(0, 1, 5, 9),\r\n"
                    + "(0, 2, 1, 9),\r\n"
                    + "(0, 2, 2, 9),\r\n"
                    + "(0, 2, 3, 9),\r\n"
                    + "(0, 2, 4, 9),\r\n"
                    + "(0, 2, 5, 9),\r\n"
                    + "(0, 3, 1, 9),\r\n"
                    + "(0, 3, 2, 9),\r\n"
                    + "(0, 3, 3, 9),\r\n"
                    + "(0, 3, 4, 9),\r\n"
                    + "(0, 3, 5, 9),\r\n"
                    + "(0, 4, 1, 9),\r\n"
                    + "(0, 4, 2, 9),\r\n"
                    + "(0, 4, 3, 9),\r\n"
                    + "(0, 4, 4, 9),\r\n"
                    + "(0, 4, 5, 9),\r\n"
                    + "(0, 5, 1, 9),\r\n"
                    + "(0, 5, 2, 9),\r\n"
                    + "(0, 5, 3, 9),\r\n"
                    + "(0, 5, 4, 9),\r\n"
                    + "(0, 5, 5, 9),\r\n"
                    + "(0, 1, 1, 10),\r\n"
                    + "(0, 1, 2, 10),\r\n"
                    + "(0, 1, 3, 10),\r\n"
                    + "(0, 1, 4, 10),\r\n"
                    + "(0, 1, 5, 10),\r\n"
                    + "(0, 2, 1, 10),\r\n"
                    + "(0, 2, 2, 10),\r\n"
                    + "(0, 2, 3, 10),\r\n"
                    + "(0, 2, 4, 10),\r\n"
                    + "(0, 2, 5, 10),\r\n"
                    + "(0, 3, 1, 10),\r\n"
                    + "(0, 3, 2, 10),\r\n"
                    + "(0, 3, 3, 10),\r\n"
                    + "(0, 3, 4, 10),\r\n"
                    + "(0, 3, 5, 10),\r\n"
                    + "(0, 4, 1, 10),\r\n"
                    + "(0, 4, 2, 10),\r\n"
                    + "(0, 4, 3, 10),\r\n"
                    + "(0, 4, 4, 10),\r\n"
                    + "(0, 4, 5, 10),\r\n"
                    + "(0, 5, 1, 10),\r\n"
                    + "(0, 5, 2, 10),\r\n"
                    + "(0, 5, 3, 10),\r\n"
                    + "(0, 5, 4, 10),\r\n"
                    + "(0, 5, 5, 10),\r\n"
                    + "(0, 1, 1, 11),\r\n"
                    + "(0, 1, 2, 11),\r\n"
                    + "(0, 1, 3, 11),\r\n"
                    + "(0, 1, 4, 11),\r\n"
                    + "(0, 1, 5, 11),\r\n"
                    + "(0, 2, 1, 11),\r\n"
                    + "(0, 2, 2, 11),\r\n"
                    + "(0, 2, 3, 11),\r\n"
                    + "(0, 2, 4, 11),\r\n"
                    + "(0, 2, 5, 11),\r\n"
                    + "(0, 3, 1, 11),\r\n"
                    + "(0, 3, 2, 11),\r\n"
                    + "(0, 3, 3, 11),\r\n"
                    + "(0, 3, 4, 11),\r\n"
                    + "(0, 3, 5, 11),\r\n"
                    + "(0, 4, 1, 11),\r\n"
                    + "(0, 4, 2, 11),\r\n"
                    + "(0, 4, 3, 11),\r\n"
                    + "(0, 4, 4, 11),\r\n"
                    + "(0, 4, 5, 11),\r\n"
                    + "(0, 5, 1, 11),\r\n"
                    + "(0, 5, 2, 11),\r\n"
                    + "(0, 5, 3, 11),\r\n"
                    + "(0, 5, 4, 11),\r\n"
                    + "(0, 5, 5, 11),\r\n"
                    + "(0, 1, 1, 12),\r\n"
                    + "(0, 1, 2, 12),\r\n"
                    + "(0, 1, 3, 12),\r\n"
                    + "(0, 1, 4, 12),\r\n"
                    + "(0, 1, 5, 12),\r\n"
                    + "(0, 2, 1, 12),\r\n"
                    + "(0, 2, 2, 12),\r\n"
                    + "(0, 2, 3, 12),\r\n"
                    + "(0, 2, 4, 12),\r\n"
                    + "(0, 2, 5, 12),\r\n"
                    + "(0, 3, 1, 12),\r\n"
                    + "(0, 3, 2, 12),\r\n"
                    + "(0, 3, 3, 12),\r\n"
                    + "(0, 3, 4, 12),\r\n"
                    + "(0, 3, 5, 12),\r\n"
                    + "(0, 4, 1, 12),\r\n"
                    + "(0, 4, 2, 12),\r\n"
                    + "(0, 4, 3, 12),\r\n"
                    + "(0, 4, 4, 12),\r\n"
                    + "(0, 4, 5, 12),\r\n"
                    + "(0, 5, 1, 12),\r\n"
                    + "(0, 5, 2, 12),\r\n"
                    + "(0, 5, 3, 12),\r\n"
                    + "(0, 5, 4, 12),\r\n"
                    + "(0, 5, 5, 12);\r\n"
                    + "\r\n"
                    + "INSERT INTO member (name, phone_number, email)\r\n"
                    + "VALUES\r\n"
                    + "('김철수', '010-1234-5678', 'chulsoo@example.com'),\r\n"
                    + "('이영희', '010-2345-6789', 'younghi@example.com'),\r\n"
                    + "('박지성', '010-3456-7890', 'jisung@example.com'),\r\n"
                    + "('정수미', '010-4567-8901', 'soomi@example.com'),\r\n"
                    + "('한민국', '010-5678-9012', 'minguk@example.com'),\r\n"
                    + "('조은하', '010-6789-0123', 'eunha@example.com'),\r\n"
                    + "('유재석', '010-7890-1234', 'jaeseok@example.com'),\r\n"
                    + "('강호동', '010-8901-2345', 'hodong@example.com'),\r\n"
                    + "('손흥민', '010-9012-3456', 'heungmin@example.com'),\r\n"
                    + "('배수지', '010-0123-4567', 'suzy@example.com'),\r\n"
                    + "('이현우', '010-1234-8901', 'hyunwoo@example.com'),\r\n"
                    + "('정우성', '010-2345-9012', 'woosung@example.com');\r\n"
                    + "\r\n"
                    + "INSERT INTO reservation (payment_method, payment_status, payment_amount, payment_date, member_id)\r\n"
                    + "VALUES\r\n"
                    + "('신용카드', 1, 12000, '2023-05-10', 1),\r\n"
                    + "('현금', 1, 12000, '2023-05-10', 1),\r\n"
                    + "('신용카드', 1, 15000, '2023-05-10', 1),\r\n"
                    + "('현금', 1, 11000, '2023-05-11', 1),\r\n"
                    + "('신용카드', 1, 13000, '2023-05-11', 1),\r\n"
                    + "('현금', 1, 14000, '2023-05-11', 1),\r\n"
                    + "('신용카드', 1, 12000, '2023-05-12', 1),\r\n"
                    + "('현금', 1, 11000, '2023-05-12', 1),\r\n"
                    + "('신용카드', 1, 10000, '2023-05-12', 1),\r\n"
                    + "('현금', 1, 13000, '2023-05-13', 1),\r\n"
                    + "('신용카드', 1, 15000, '2023-05-13', 1),\r\n"
                    + "('현금', 1, 14000, '2023-05-13', 1);\r\n"
                    + "\r\n"
                    + "INSERT INTO ticket (is_ticketed, screening_schedule_id, seat_id, reservation_id, screen_id)\r\n"
                    + "VALUES\r\n"
                    + "(1, 1, 1, 1, 1),\r\n"
                    + "(1, 2, 2, 2, 1),\r\n"
                    + "(1, 3, 3, 3, 2),\r\n"
                    + "(1, 4, 4, 4, 3),\r\n"
                    + "(1, 5, 5, 5, 4),\r\n"
                    + "(1, 6, 6, 6, 5),\r\n"
                    + "(1, 7, 7, 7, 6),\r\n"
                    + "(1, 8, 8, 8, 7),\r\n"
                    + "(1, 9, 9, 9, 8),\r\n"
                    + "(1, 10, 10, 10, 9),\r\n"
                    + "(1, 11, 11, 11, 10),\r\n"
                    + "(1, 12, 12, 12, 11);";

}
